/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.forms;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import org.util.CommonUtility;


/**
 *
 * @author Shibaji
 */
public class RestaurantMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form RestaurantMainMenu
     */
    private JDesktopPane desktopPane = null;
    public RestaurantMainMenu() {
        initComponents();
        desktopPane = new JDesktopPane();
        this.setContentPane(desktopPane);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuMenuItems = new javax.swing.JMenu();
        jMenuItemMenuItem = new javax.swing.JMenuItem();
        jMenuItemOrder = new javax.swing.JMenuItem();
        jMenuItemOrderSearch = new javax.swing.JMenuItem();
        jMenuItemKitchenOrder = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenuMenuItems.setText("Master");

        jMenuItemMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemMenuItem.setText("MenuItems");
        jMenuItemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMenuItemActionPerformed(evt);
            }
        });
        jMenuMenuItems.add(jMenuItemMenuItem);

        jMenuItemOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOrder.setText("Order");
        jMenuItemOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrderActionPerformed(evt);
            }
        });
        jMenuMenuItems.add(jMenuItemOrder);

        jMenuItemOrderSearch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemOrderSearch.setText("Order Search");
        jMenuItemOrderSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrderSearchActionPerformed(evt);
            }
        });
        jMenuMenuItems.add(jMenuItemOrderSearch);

        jMenuItemKitchenOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemKitchenOrder.setText("Kitchen Order");
        jMenuItemKitchenOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItemKitchenOrderMouseReleased(evt);
            }
        });
        jMenuMenuItems.add(jMenuItemKitchenOrder);

        jMenuBar1.add(jMenuMenuItems);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jMenuItemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                                  
      //  MenuMasterFrame masterFrame = new MenuMasterFrame();
      //  desktopPane.add(masterFrame);
      //  masterFrame.setVisible(true);
        
        
        Invoice oo=new Invoice();
        CommonUtility.positionAtCenterOfMDI(oo, desktopPane);
//CommonUtility.positionAtCenterOfScreen(desktopPane);
        desktopPane.add(oo);
        oo.setVisible(true);
    }                                                 

    private void jMenuItemOrderActionPerformed(java.awt.event.ActionEvent evt) {                                               
       //OrderFrame orderFrame =new OrderFrame();
       //desktopPane.add(orderFrame);
      // CommonUtility.positionAtCenterOfMDI(orderFrame, desktopPane);
      // orderFrame.setVisible(true);
    }                                              

    private void jMenuItemOrderSearchActionPerformed(java.awt.event.ActionEvent evt) {                                                     
       
    }                                                    

    private void jMenuItemKitchenOrderMouseReleased(java.awt.event.MouseEvent evt) {                                                    
        
    }                                                   
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantMainMenu().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify                     
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemKitchenOrder;
    private javax.swing.JMenuItem jMenuItemMenuItem;
    private javax.swing.JMenuItem jMenuItemOrder;
    private javax.swing.JMenuItem jMenuItemOrderSearch;
    private javax.swing.JMenu jMenuMenuItems;
    // End of variables declaration                   
}
